# Generated by Django 4.2.3 on 2023-09-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='Hello, i am a new one here'),
        ),
    ]
